name: mcb
description: "Minecraft Box"
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_colorpicker: ^1.1.0
  json_rpc_2: ^4.0.0
  web_socket_channel: ^3.0.3
  crypto: ^3.0.6
  dio: ^5.9.0
  encrypt: ^5.0.3
  package_info_plus:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_plus_plugins.git"
      path: "packages/package_info_plus/package_info_plus"
  shared_preferences:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
  url_launcher:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
      path: "packages/url_launcher/url_launcher"
  device_info_plus:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_plus_plugins.git"
      path: "packages/device_info_plus/device_info_plus"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/img/icon/
    - assets/img/logo/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansCJKsc-VF.ttf